FROM ubuntu:18.04
MAINTAINER Takenobu Tani <takenobu.hs@gmail.com>

# GHC building for
#   ubuntu18.04LTS + ghc8.8

ENV LANG     C.UTF-8
ENV LC_ALL   C.UTF-8
ENV LANGUAGE C.UTF-8

# Preparation
# -----------
#   [1]: https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Linux
#
RUN apt-get update; \
    apt-get -y install git autoconf automake libtool make gcc g++ \
                       libgmp-dev ncurses-dev libtinfo-dev python3 xz-utils

RUN apt-get install wget; \
    mkdir tmp.haskell-platform; \
    cd tmp.haskell-platform; \
    wget https://haskell.org/platform/download/8.4.3/haskell-platform-8.4.3-unknown-posix--core-x86_64.tar.gz; \
    tar xzf haskell-platform-8.4.3-unknown-posix--core-x86_64.tar.gz; \
    ./install-haskell-platform.sh; \
    cd ..; \
    rm -fr tmp.haskell-platform; \
    cd /usr/local/haskell/ghc-8.4.3-x86_64/lib/ghc-8.4.3; \
    sed -ie 's/^, ("C compiler supports -no-pie","NO")/, ("C compiler supports -no-pie","YES")/' settings

## -- For building the documentation (User's Guide)
# RUN apt-get -y install python-sphinx texlive-xetex texlive-fonts-recommended \
#                        fonts-lmodern texlive-latex-recommended \
#                        texlive-latex-extra; \
#     apt-get -y install linux-tools-generic xutils-dev


# Getting the GHC sources
# -----------------------
#   [2]: https://ghc.haskell.org/trac/ghc/wiki/Building/GettingTheSources
#
RUN cd; \
    mkdir ghc_build; \
    cd ghc_build; \
    git clone -b ghc-8.8 --recurse-submodules https://gitlab.haskell.org/ghc/ghc.git ghc-8.8; \
    cd ghc-8.8; \
    git checkout ghc-8.8; \
    git submodule update --init


# Building
# --------
#   [3]: https://ghc.haskell.org/trac/ghc/wiki/Building/QuickStart
#
RUN cd; \
    cd ghc_build/ghc-8.8; \
    cd mk; \
    sed -e 's/^#BuildFlavour = quick$/BuildFlavour = quick/' \
        build.mk.sample > build.mk; \
    cd ..; \
    ./boot; \
    ./configure; \
    make -j 9			# change here for your cpu number

# -> generated your ./inplace/bin/ghc-stage2


# Validation
# ----------
#   [4]: https://ghc.haskell.org/trac/ghc/wiki/TestingPatches
#
#RUN cd;\
#    cd ghc_build/ghc-8.8; \
#    THREADS=9 ./validate                 # full validation
##   ./validate --fast --testsuite-only   # fast validation


# See also
# --------
#   [5]: https://ghc.haskell.org/trac/ghc/wiki/Newcomers
#
